export const configs = {
  RECEITA_BRANCA_URL: process.env.NEXT_PUBLIC_CREATE_RECEITA_BRANCA,
  RECEITA_ANTIMICROBIANA_URL:
    process.env.NEXT_PUBLIC_CREATE_RECEITA_ANTIMICROBIANA,
  RECEITA_NOTIFICACAO: process.env.NEXT_PUBLIC_CREATE_RECEITA_NOTIFICACAO,
}
